sudo: required
services:
  - docker

before_install:
  - docker build -t ethicho/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ethicho/react-test npm test

after_success:
  - docker build -t neocycf/multi-client ./client
  - docker build -t neocycf/multi-nginx ./nginx
  - docker build -t neocycf/multi-server ./server
  - docker build -t neocycf/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push neocycf/multi-client
  - docker push neocycf/multi-nginx
  - docker push neocycf/multi-server
  - docker push neocycf/multi-worker
